# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5e54b43fe0f313b7b06ddca87e48d36397b78775d13c2a62d513933f7c2c34cab80d42cf212c6745d07e46c1649dc5c768a58dc36c644a51c31b8a6bde3d38f3

test:
  secret_key_base: 49113fd14ded3d6960a311b2612037bbfb46a96f171274a86aaac32c8a360726b35e1e665c23431ed4b05d0e291137c3cb6117daf7231f8af0452e666397602b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
